export const IconCategory = {
  WALL_DESIGN: 'wallDesign',
  SHEET_BOUNDED: 'sheetBounded',
  POCKET_DESIGN: 'pocketDesign',
  TILT_DESIGN: 'tiltDesign',
  MULLION: 'mullion',
  ADD_ONS: 'addOns',
  COUPLER: 'coupler',
  CUSTOM: 'custom',
  DESIGN: 'design',
  LIFT_AND_SLIDE: 'liftAndSlide',
  MONORAIL: 'monorail',
  PARTITION: 'partition',
  PIVOT: 'pivot',
  PLEATED_AND_PULL_DOWN_MESH: 'pleatedAndPullDownMesh',
  ZIGZAG_DESIGN: 'zigzagDesign',
  SASH_DESIGN: 'twinSashDesign',
  SLIDING: 'sliding',
  OTHER_ICONS: 'otherIcons',
} as const;
